#!/usr/bin/env bash

set -euo pipefail

! git config --get remote.origin.url &> /dev/null && echo 'This is not a git repository.' && exit 1

if git diff-index --quiet HEAD -- &> /dev/null; then
    git pull
else
    git stash
    git pull
    git stash pop
fi