#!/usr/bin/env bash

set -euo pipefail

! git config --get remote.origin.url &> /dev/null && echo 'This is not a git repository.' && exit 1

if [[ -z ${1+x} ]] && [[ -z ${2+x} ]]; then
    git fetch origin
    git merge origin/master
elif [[ -z ${2+x} ]]; then
    git fetch $1
    git merge $1/master
else
    git fetch $1
    git merge $1/$2
fi